modLoader="javafml"
loaderVersion="[39,)"
license="All Rights Reserved"
[[mods]]
modId="overweight_farming"
version="1.18.2-1.5.3-forge"
displayName="Overweight Farming"
displayURL="https://discord.com/invite/sA858vGruu"
authors="Binome, Orcinus"
logoFile="overweight_farming_logo.png"
description='''
This mod enhances the farming system
'''
[[dependencies.overweight_farming]]
   modId="forge"
   mandatory=true
   versionRange="[39,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.overweight_farming]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.18.1,1.19)"
   ordering="NONE"
   side="BOTH"
