modLoader="javafml"
loaderVersion="[39,)"
license="All Rights Reserved"
[[mods]]
modId="overweight_farming"
version="1.18.2-1.3.1-forge"
displayName="Overweight Farming"
authors="Binome, Orcinus"
description='''
This mod enhances the farming system
'''
[[dependencies.overweight_farming]]
   modId="forge"
   mandatory=true
   versionRange="[39,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.overweight_farming]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.18.1,1.19)"
   ordering="NONE"
   side="BOTH"
